# Generated by Django 5.1 on 2024-09-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='name in arabic')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('size_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='size in arabic')),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='name in arabic')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description in arabic')),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.categories')),
                ('sizes', models.ManyToManyField(blank=True, null=True, related_name='products', to='products.sizes')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
